### ISSUE TITLE
Project named in a misleading manner

### ISSUE THREAD

**Issue by philipn** [s3git/s3git#1]
This project does not appear to implement the `git` protocol. I would suggest renaming the project, as people may be confused by the current name.

**Comment by fwessels** [comment]
This project tries to combine the cloud storage world in which S3 is pretty much the de-facto standard with the git philosophy and spirit of working, and hence the name was chosen as the concatenation of the two names.

**Comment by vovcacik** [comment]
Brief clarification in readme would do some good.

**Comment by philipn** [comment]
I totally disagree here.  If you weren't supporting S3, would you use the S3 name?  The project name is misleading.  I think this issue should be reopened or the project renamed.

**Comment by fwessels** [comment]
I have added a clarification in the README that both are not binary compatible.

**Comment by fwessels** [comment]
@philipn  If the project had no connection to S3 then we wouldn’t have referred to it just like if it had no connection to git. 
But that is not to say that it is ‘exactly’ this or that, in fact some people may mistake the ‘s3’ part of the name for it to be an ‘S3’ server for all we know which it is obviously not.

The first line of the README says that it applies the _git philosophy_ to cloud storage and we’ve added an FAQ about compatibility (see above). Also if you glance over the README you will instantly recognise differences like BLAKE2 hashing, more than 2x longer hashes, etc. so we don’t see the confusion.

**Comment by philipn** [comment]
It *does* implement the S3 protocol, hence it can be used with the S3 service.  It *does not* implement the git protocol, and thus it is confusing and misleading that it contains `git` so prominently in its name.  There are a variety of hash-based 

Almost everyone finding this package will be looking for something like "a way to use git on s3."  This package will seem like just what they were looking for, until they look carefully.
